### ISSUE TITLE
Why generated 0 features from 5ns protein's trajectory

### ISSUE THREAD

**Issue by kingljy0818** [schallerdavid/pyrod#2]
Dear David,

I recently used pyrod to explore the pharmacophore of the protein. This protein has been made into a 5ns MD using amber16, then the trajectory has been converted into a .nc format trajectory using cpptraj with autoimage parameter. When I performed  "pyrod trajectory_pharmacophore_combo.cfg" (using the default parameters), the log shows that 0 features are generated. Due to I am a long-time user of ligandscout. I opened a * .pml file with ligandscout and only displayed Exclusion Volumes balls. Would you help me to solve this problem, many thanks.

Kindest regards

Jiyuan

**Comment by schallerdavid** [comment]
Dear Jiyuan,

thanks for your interest in PyRod. Did you adjust the `center` and `edge_length` parameters in the trajectory_pharmacophore_combo.cfg to indicate the part of the protein you are interested in? There is a test_grid.cfg available that can be used to adjust these parameters. It essentially generates grids in pdb format that correspond to the area PyRod would analyze in the later trajectory processing.

Best regards,

David

**Comment by kingljy0818** [comment]
Dear David,

Thank you for your quick response. Actually, I have predicted the active center of the protein, and performed the test_grid.cfg using pyrod.  But I could not get any features, and the log in the follow:
--------------------------------------------------------------------------------------------------
Starting trajectory analysis.
Initializing grid.
Analyzing 1000 frames from 1 trajectory.
Progress of trajectory analysis: [==========] 100.0%         Done
Processing results.
Writing raw data to /home/Molecule Dynamics/Pyrod_Test/pyrod/data.
Writing maps to /home/Molecule Dynamics/Pyrod_Test/pyrod/dmifs.
Generating exclusion volumes.
Progress of exclusion volume generation: [==========] 100.0%         Done
Finished with generation of 37 exclusion volumes.
Generating features.
Progress of feature generation: [==========] 100.0%         Done
Generated 0 features.
Writing pharmacophore with all features to /home/Molecule Dynamics/Pyrod_Test/pyrod/pharmacophores.
Finished after 3.9 min.
----------------------------------------------------------------------------------------------------------

I also attached the top file (49kda_h2o.pdb), and the pyrod scripts in Lab.zip, would you have a check and help me to solve this problem, many thanks.

Kindest regards

Jiyuan
[Lab.zip](https://github.com/schallerdavid/pyrod/files/4706052/Lab.zip)

**Comment by schallerdavid** [comment]
Hey Jiyuan,

I checked the files you sent and it appears that PyRod recognizes the system correctly. I used the provided pdb file for the `topology` and for the `trajectories` parameter in the trajectory_pharmacophore_combo.cfg. PyRod generated several features with these settings. 

Other issues I could think of:
1. Something is wrong with your trajectory. Did you check visually that alignment and centering of the protein in the water box was successful for all frames of the trajectory?

2. Different versions. I just pulled the newest version oy PyRod and run it with Python 3.6.4, MDAnalysis 0.19.2.

If that doesnt help, you could also sent me 5 frames of your trajectory and I will have a look.

David

**Comment by kingljy0818** [comment]
Dear David,

1. R: I usually check the protein in the center of the water box in VMD when I performed pyrod before.

2.  R: I installed pyrod following the installation tutorial in pyrod wiki:

just run the command 'conda create -n pyrod mdanalysis python=3.8'

I have attached 5 frames, the .prmtop file, the cpptraj script centering the protein and the pyrod scripts in Lab_1.zip. Would you have a check and help me to solve this problem. Many thanks.

Best regards

Jiyuan

[Lab_1.zip](https://github.com/schallerdavid/pyrod/files/4707849/Lab_1.zip)

**Comment by kingljy0818** [comment]
Dear David,

I have found the problem. The autoimage.cpptraj in the last attachment was the reason, it could be modified in the follow:
-----------------------------
trajin prod1.mdcrd
center origin :1-387 
image origin center 
trajout prod.dcd
-----------------------------

The trajectory of prod.dcd was generated the features by performed 'pyrod trajectory_pharmacophore_combo'.

Kindest regards

Jiyuan
