### ISSUE TITLE
Other trajectory file formats that can be used in pyrod analysis

### ISSUE THREAD

**Issue by pravzK94** [schallerdavid/pyrod#4]
Hi! 

I want to use pyrod for water pharmacopore modelling towards a multi-targeting drug design. In regards with this I have been running 10ns TIP4Ew simulation with amber14 force field for my targets. My question is will pyrod accept trajectory files generated in .pdb format from these simulation? 
If not please. specify the file formats that are preferred for analysis through pyrod?

**Comment by schallerdavid** [comment]
Hi @EvilScience94 ,
thanks for your interest in using PyRod. PyRod uses MDAnalysis under the hood to handle topology and trajectory files. So please have a look at the corresponding [documentation](https://userguide.mdanalysis.org/1.0.0/formats/index.html). Also, you could try reading your files with MDAnalysis outside PyRod to see if you get a proper handling of topology and trajectory.
All the best,
David

**Comment by pravzK94** [comment]
Hello David!

Thank you for your prompt response. Checked the documentation of MDanalysis and it does have .pdb file handling. Will definitely try out first with MDanalysis.

Thanks and regards
Praveena

**Comment by pravzK94** [comment]
Hi David

I have installed pyrod on linux. I have been trying to run the program as directed, but the following error is encountered:
Traceback (most recent call last):
  File "pyrod.py", line 65, in <module>
    directory = config.get('directory', 'directory')
  File "/usr/lib/python3.8/configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "/usr/lib/python3.8/configparser.py", line 1149, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'directory'

and I have also created the config file as directed. Below is the format in which it has been written

[directory]
directory: /home/praveenak/Downloads/pyrod-master/Multi

[trajectory analysis parameters]
center: 0, 0, 0
edge lengths: 90, 90, 90
topology: /home/praveenak/Downloads/pyrod-master/Rv0827c_tip4pew_1904.pdb
trajectories: /home/praveenak/Downloads/pyrod-master/Rv0827c_1904.pdb 
first frame: 999
last frame:
step size:
metal names:
map formats: cns, xplor, knot
number of processes: 1

[exclusion volume parameters]
shape cutoff: 1
restrictive: false

[features parameters]
number of processes: 1
features per feature type: 20

[pharmacophore parameters]
pharmacophore formats: pdb, pml

I request to please help me figure out where I am going wrong in executing the same.

**Comment by pravzK94** [comment]
Hi David

i have figured out the mistake and error where it was going wrong. 

Thank you
Praveena K
