### ISSUE TITLE
Generating 0 exclusion volumes and features for a 10ns protein

### ISSUE THREAD

**Issue by pravzK94** [schallerdavid/pyrod#5]
[traj_Rv0827c.txt](https://github.com/wolberlab/pyrod/files/8621082/traj_Rv0827c.txt)
Hi David,

I have been trying to attain a super pharmacophore for a 10ns simulation run in TIP4Pew water model. After the trajectory analysis, the program is resulting in generation of 0 exclusion volumes and thus, 0 features. Can you please help me out in troubleshooting? Here i am attaching the config file for your perusal. 
Please help us out in figuring out the mistake, where we are going wrong. 

Thanks and regards
Praveena K

**Comment by schallerdavid** [comment]
Hi @EvilScience94 ,

I can't spot any obvious problems in the config file, but here are some things you could check:
 - first frame is set to 1001 --> this means the first 1000 frames of the trajectory will be skipped, how many do you have in the trajectory?
 - you defined the location of the grid with the center and edge length parameters, did you check if the recentered trajectory stays in this area over the course of the 10 ns?
 - for the feature generation it is not an immediate problem, but I remember ligandscout has problems visualizing non-cubic grids, if you intend to use ligandscout for this consider an edge length of e.g. 30, 30, 30

Please let me know if you were able to solve the problem!

All the best,
David
