### ISSUE TITLE
Shift in the density maps

### ISSUE THREAD

**Issue by sepehrd2** [schallerdavid/pyrod#6]
Hi,

I am inputting an AMBER trajectory into pyrod. The issue that I am facing is that the density maps shift a bit when I compare them to the water density that I calculated from the trajectory. I was wondering if you could tell me why this shift is happening and how I can fix it.

Thanks,
Sepehr

**Comment by schallerdavid** [comment]
Hi @sepehrd2 ,
could you provide images to examplify the problem. As long as both were calculated from the same aligned trajectory, there should not be a big difference.
