### ISSUE TITLE
Unable to perform ROC analysis with helper script

### ISSUE THREAD

**Issue by martinlju** [schallerdavid/pyrod#9]
Hi David,

I have used Pyrod to successfully generate a super pharmacophore. Afterwards, I selected potentially important features and generated a combinatorial library, which consists of 404 pharmacophores. I then tried using the Python helper script (library_roc_analysis.py) to perform an ROC analysis of the pharmacophores. Unfortunately, the script is not able to perform the analysis in my case. I am running the script on a Windows 10 computer with Python 3.10 and LigandScout 4.4.3

While the program is running, it continuously outputs the same message (Analyzing pharmacophore 0 of 404.). However, it does not make any progress. Here is the entire output after I interrupted it manually (otherwise it would continue running indefinitely):

![screening_problem](https://github.com/wolberlab/pyrod/assets/122090439/714c777d-41c3-48fd-aa1f-503eaeba7f77)

The only file that gets created is roc_statistics.txt (with no results):
[roc_statistics.txt](https://github.com/wolberlab/pyrod/files/12320653/roc_statistics.txt)

I have also tried running it through the command line in Windows, but it is also stuck at the start (Analyzing pharmacophore 0 of 404.). This is the output when cancelling the process:

Analyzing pharmacophore 0 of 404.Traceback (most recent call last):
  File "C:\Users\martinl\Dropbox\PC\Desktop\SRC KNASE\PYROD_real\lck_last100frames\PYROD_HELPERSCRIPT\library_roc_analysis_LS_local.py", line 173, in <module>
    subprocess.run('{0} -q {1}.pml -d {2}:active -o {1}.sdf -l {1}.log -C {3} -M {4}'.format(
  File "C:\Users\martinl\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\martinl\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\martinl\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt

Here are the files I used, including the python script:
[test_files.zip](https://github.com/wolberlab/pyrod/files/12320643/test_files.zip)

I am otherwise able to load the files into Ligandscout and perform an ROC analysis individually on each pharmacophore with no problems. I suspect there might be an issue with program versions, but I have not been able to locate the problem. I would greatly appreciate any help.

Thank you and regards,
Martin

**Comment by schallerdavid** [comment]
Hi Martin,
any chance you can try this on linux? I never tried calling ligandscout from the command line in windows. Maybe the Problem comes from this. Also, I did not update any code for the newer python releases, so testing this with a python 3.8 environment might be worth a try as well.

**Comment by martinlju** [comment]
Dear David,

thank you for your reply and suggestion. I have tried to run the script on linux as well, but had the same problem. Sadly, using an older Python version also didn't help.

Thanks and kind regards,
Martin

**Comment by schallerdavid** [comment]
Dear Martin,

could you manually execute the first run via the command line? 
First change in the terminal to the respective directory and then execute something like
```
C:\Program Files\LigandScout 4.0\iscreen.exe -q library/0.pml -d handpicked_screenlibrary.ldb:active -o 0.sdf -l 0.log -C  6 -M 8
```

**Comment by martinlju** [comment]
Dear David,

I manually executed the command (I needed to put the iscreen path in quotations to avoid the error: 'C:\Program' is not recognized as an internal or external command, operable program or batch file.)
`"C:\Program Files\LigandScout 4.0\iscreen.exe" -q library/320.pml -d handpicked_screenlibrary.ldb:active -o "320.sdf" -l "320.log" -C  6 -M 8`

The program worked. I did this for several pharmacophores, here is an example of pharmacophore 310, which produces hits:

Screening (10 hits)  [=========================================] 100,000%
iscreen finished successfully.

The program did not always execute instantly, sometimes I had to wait up to 30 seconds for it to start (it worked fast once it actually began running)

Log file from executing the command above:
[320.log](https://github.com/wolberlab/pyrod/files/12410669/320.log)

**Comment by schallerdavid** [comment]
Dear Martin,

I think we found the problem :), its about the whitespaces. Could you put the iscreen executable in quotations in the python file?

```
iscreen_path = '"C:\Program Files\LigandScout 4.0\iscreen.exe"'
```

**Comment by martinlju** [comment]
Dear David,

you are right, the problem was with the whitespaces all along. The script works now that I've added the quotations.

Thank you again for all of your help! 

Best regards,
Martin
